version: '3'
services: 

  php:
    # image: php:7-fpm
    build: 
      context: ./docker
      dockerfile: php.Dockerfile
    volumes:
      - './app:/var/www/html'
    links:
      - 'db'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - './app:/var/www/html'
      - './config/nginx:/etc/nginx/conf.d'
      - './ssl:/etc/nginx/ssl/'

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - './db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data


  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123!"
      PGADMIN_LISTEN_PORT: 80
    ports: 
      - '16543:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    links:
      - 'db:pgsql-server'

volumes:
  db-data:
  pgadmin-data:

